name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      run: |
        sudo apt update
        sudo apt install autopoint
        sudo apt install flex 
        sudo apt install bison 
        sudo apt install libncurses5-dev
    - name: cmake
      run: |
        cd build
        mkdir linux
        cd linux
        cmake ../..
    - name: make
      run: |
        cd build/linux
        make
